import {Inter} from "next/font/google";
// common styles for all
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        {/*even if you wrap the application with a client side component, its just a wrapper, rest of applications are server side components*/}
        {/* <ClientSideProviderTest> */}
        <div className="container">
            <Navbar/>
            {children}
            <Footer/>
        </div>
        {/* </ClientSideProviderTest> */}
        </body>
        </html>
    );
}
